Repository doc-detective/doc-detective, pull requests merged in 2024-07, with the labels that each got.

#75 v2.14.0
  package-lock.json
  package.json
Labels: enhancement, size:XS

#77 Support file names in `output`
  package-lock.json
  package.json
  src/index.js
  src/utils.js
Labels: dependencies, size:M

#78 Update doc-detective-core to version 2.15.1
  package-lock.json
  package.json
Labels: dependencies, size:XS

#80 Relative file paths
  package-lock.json
  package.json
  src/index.js
  src/utils.js
  test/artifacts/config.json
  test/artifacts/httpRequest.spec.json
  test/artifacts/test.spec.json
  test/runCoverage.test.js
  test/runTests.test.js
  test/utils.test.js
Labels: enhancement, size:M

#82 v2.16.0
  package-lock.json
  package.json
  src/index.js
  src/utils.js
  test/artifacts/config.json
  test/artifacts/httpRequest.spec.json
  test/artifacts/test.spec.json
  test/runCoverage.test.js
  test/runTests.test.js
  test/utils.test.js
Labels: enhancement, dependencies, size:M

#81 Yaml input support
  src/index.js
  src/utils.js
  test/artifacts/config.yaml
  test/runTests.test.js
Labels: enhancement, size:M
